//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectsID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public string ImageURL { get; set; }
        public string GitHubURL { get; set; }
    }
}
